#!/bin/bash

# Script to rename quote graphics based on their text content
# Using dash-case format for filenames

cd "/Volumes/Development/narcissist-book/social/images/raw" || exit

echo "Renaming images based on quote text..."
echo ""

# Rename each image based on the quote text
mv "1_(Bulk 5) Success is getting what you want. Happiness is wanting what you get..png" "youre-not-broken-youre-traumatized.png"
mv "2_(Bulk 9) Truth Over Tactic Quotes.png" "youre-doing-better-than-you-think.png"
mv "3_(Bulk 4) Success is getting what you want. Happiness is wanting what you get..png" "this-is-your-story-to-reclaim.png"
mv "4_(Bulk 9) Success is getting what you want. Happiness is wanting what you get..png" "from-chaos-clarity-is-possible.png"
mv "5_(Bulk 16) Truth Over Tactic Quotes.png" "you-control-your-healing-pace.png"
mv "6_(Bulk 12) Truth Over Tactic Quotes.png" "your-body-knows-the-truth.png"
mv "7_(Bulk 10) Truth Over Tactic Quotes.png" "all-your-feelings-are-normal.png"
mv "8_(Bulk 18) Truth Over Tactic Quotes.png" "this-pain-is-real-but-not-permanent.png"
mv "9_(Bulk 13) Truth Over Tactic Quotes.png" "the-chaos-is-real-deliberate-and-abuse.png"
mv "10_(Bulk 7) Success is getting what you want. Happiness is wanting what you get..png" "just-start-documenting-everything-else-can-wait.png"
mv "11_(Bulk 11) Truth Over Tactic Quotes.png" "youre-a-survivor-not-an-abuser.png"
mv "12_(Bulk 6) Truth Over Tactic Quotes.png" "your-love-was-real-their-mask-was-not.png"
mv "13_(Bulk 12) Truth Over Tactic Quotes.png" "real-love-doesnt-hurt.png"
mv "14_(Bulk 18) Success is getting what you want. Happiness is wanting what you get..png" "lift-the-mask-choose-yourself.png"
mv "15_(Bulk 1) Truth Over Tactic Quotes.png" "the-mask-is-slipping-you-decide-whats-next.png"
mv "16_(Bulk 13) Truth Over Tactic Quotes.png" "theres-no-timeline-for-leaving-abuse.png"
mv "17_(Bulk 1) Success is getting what you want. Happiness is wanting what you get..png" "you-survived-100-percent-of-your-worst-days.png"
mv "18_(Bulk 6) Success is getting what you want. Happiness is wanting what you get..png" "safety-planning-comes-first.png"
mv "19_(Bulk 15) Truth Over Tactic Quotes.png" "understanding-trauma-bonding-gives-you-power-to-break-it.png"
mv "20_(Bulk 8) Truth Over Tactic Quotes.png" "reading-this-is-a-step-youre-building-awareness.png"
mv "21_(Bulk 5) Truth Over Tactic Quotes.png" "you-cant-win-their-smear-campaign-let-your-truth-speak.png"
mv "22_(Bulk 15) Success is getting what you want. Happiness is wanting what you get..png" "the-mask-is-slipping-you-decide-whats-next-2.png"
mv "23_(Bulk 11) Truth Over Tactic Quotes.png" "your-self-doubt-is-their-manipulation-working.png"
mv "24_(Bulk 12) Success is getting what you want. Happiness is wanting what you get..png" "understanding-is-the-first-step-to-freedom.png"
mv "25_(Bulk 6) Truth Over Tactic Quotes.png" "the-shame-ends-here.png"
mv "26_(Bulk 17) Truth Over Tactic Quotes.png" "you-survived-the-inescapable-youre-breaking-free.png"
mv "27_(Bulk 14) Truth Over Tactic Quotes.png" "youre-remembering-who-you-are.png"
mv "28_(Bulk 4) Truth Over Tactic Quotes.png" "the-mask-was-the-lie-truth-is-your-freedom.png"
mv "29_(Bulk 8) Truth Over Tactic Quotes.png" "every-day-of-no-contact-is-progress.png"
mv "30_(Bulk 19) Success is getting what you want. Happiness is wanting what you get..png" "real-love-doesnt-hurt-2.png"
mv "31_(Bulk 1) Truth Over Tactic Quotes.png" "youre-not-just-surviving-youre-preparing-to-thrive.png"
mv "32_(Bulk 2) Success is getting what you want. Happiness is wanting what you get..png" "from-chaos-clarity-from-fear-freedom.png"
mv "33_(Bulk 15) Truth Over Tactic Quotes.png" "it-was-that-bad.png"
mv "34_(Bulk 16) Truth Over Tactic Quotes.png" "your-experience-is-valid.png"
mv "35_(Bulk 20) Truth Over Tactic Quotes.png" "documentation-makes-your-truth-undeniable.png"
mv "36_(Bulk 14) Success is getting what you want. Happiness is wanting what you get..png" "your-capacity-to-love-is-strength-not-weakness.png"
mv "37_(Bulk 3) Success is getting what you want. Happiness is wanting what you get..png" "youre-not-broken-youre-healing-from-trauma.png"
mv "38_(Bulk 4) Truth Over Tactic Quotes.png" "drama-is-their-fuel-boredom-is-your-boundary.png"
mv "39_(Bulk 2) Truth Over Tactic Quotes.png" "their-chaos-will-exhaust-itself-your-clarity-wont.png"
mv "40_(Bulk 9) Truth Over Tactic Quotes.png" "progress-not-perfection-youre-doing-better-than-you-think.png"
mv "41_(Bulk 10) Success is getting what you want. Happiness is wanting what you get..png" "this-is-a-marathon-not-a-sprint.png"
mv "42_(Bulk 17) Success is getting what you want. Happiness is wanting what you get..png" "their-rage-isnt-your-fault.png"
mv "43_(Bulk 19) Truth Over Tactic Quotes.png" "youre-not-crazy-you-see-the-pattern-now.png"
mv "44_(Bulk 11) Success is getting what you want. Happiness is wanting what you get..png" "you-control-your-healing-pace-2.png"
mv "45_(Bulk 8) Success is getting what you want. Happiness is wanting what you get..png" "documentation-is-your-defense.png"
mv "46_(Bulk 17) Truth Over Tactic Quotes.png" "youre-not-weak-youre-surviving-psychological-warfare.png"
mv "47_(Bulk 5) Truth Over Tactic Quotes.png" "you-stayed-because-your-brain-was-hijacked.png"
mv "48_(Bulk 7) Truth Over Tactic Quotes.png" "your-integrity-will-speak-eventually.png"
mv "49_(Bulk 16) Success is getting what you want. Happiness is wanting what you get..png" "lift-the-mask-choose-yourself-2.png"
mv "50_(Bulk 10) Truth Over Tactic Quotes.png" "none-of-this-was-your-fault.png"
mv "51_(Bulk 3) Truth Over Tactic Quotes.png" "seeing-clearly-is-painful-and-powerful.png"
mv "52_(Bulk 19) Truth Over Tactic Quotes.png" "take-breaks-youre-in-control.png"
mv "53_(Bulk 13) Success is getting what you want. Happiness is wanting what you get..png" "your-love-was-real-their-mask-was-not-2.png"
mv "54_(Bulk 18) Truth Over Tactic Quotes.png" "distance-is-healing-even-when-invisible.png"
mv "55_(Bulk 7) Truth Over Tactic Quotes.png" "trauma-bonds-can-be-broken.png"
mv "56_(Bulk 2) Truth Over Tactic Quotes.png" "trust-your-reality-over-their-performance.png"
mv "57_(Bulk 3) Truth Over Tactic Quotes.png" "stop-rescuing-them-let-the-pattern-show.png"
mv "58_(Bulk 14) Truth Over Tactic Quotes.png" "they-seemed-nice-to-others-you-know-the-truth.png"

echo ""
echo "✓ All images renamed successfully!"
echo ""
echo "Images now have descriptive, dash-cased filenames based on their quote text."
